dist: trusty
language: node_js
node_js: 6

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm prune
  - npm install

script:
  - npm run ci

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
