dist: trusty
language: node_js
node_js: 8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm prune
  - npm install

script:
  - while [ ! -e /tmp/.X11-unix/X99 ]; do sleep 0.1; done
  - npm run test:ci

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
